spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 500000
      connection-timeout: 30000
      idle-timeout: 600000
      max-pool-size: 10
      minimum-idle: 2
      pool-name: HikariCP
      auto-commit: true
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 6365
  undertow:
    threads:
      worker: 20
      io: 2
    buffer-size: 1024
    direct-buffers: true
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt-secret: ${JWT_SECRET}
log-dir: ${LOG_DIR}


captcha:
  init-default-resource: true
  secondary:
    enabled: true
    expire: 120000
